### ISSUE TITLE
OpenSHMEM 1.4 API  - tracking issue

### ISSUE THREAD

**Issue by hppritcha** [openshmem-org/openshmem#48]
This issue tracks progress toward making the reference OpenSHMEM implementation compliant with the OpenSHMEM 1.4 Specification.

- [ ] Implement the communication _context_ functions.  See additions to Section 8.4.
- [ ] Implement ```shmem_sync_all``` and ```shmem_sync``` routines.  See Sections 8.8.3 and 8.8.4.
- [ ] Add ```SHMEM_SYNC_SIZE``` constant.  See Section 6.
- [ ] Add type-generic interfaces for ```SHMEM_WAIT```.
- [ ] Remove ```volatile``` qualifiers from certain arguments to ```shmem_wait``` and lock API functions.  See sections 8.9.1 and 8.11.1.
- [ ] Deprecate ```SMA_``` prefixed environment variables and add ```SHMEM_``` prefixed equivalents.  See section 7.
- [ ] Add C11 ```_Noreturn``` to ```shmem_global_exit```.  See section 8.1.5
- [ ] Deprecate the ```shmem_wait``` functions and add ```shmem_test``` functions.  See section 8.9
- [ ] Implement ```shmem_calloc```.  See section 8.3.2
- [ ] Implement ```shmem_init_thread``` and ```shmem_query_thread```.  See sections 8.2.1 and 8.2.2.
- [ ] Implement new atomic memory operations.  See sections 8.5 and 8.7
- [ ] Replace ```complex``` macro with C99 ```_Complex``` definition.  See section 8.8.7.
- [ ] Check man pages since some APIs variable changes occurred with 1.4.
